cache:
  paths:
    - subprojects/packagecache/

before_script:
  - ./tools/clean.sh meson

test_gcc:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --gcc

test_fedora_gcc:
  image: greenaddress/fedora_ci@sha256:218c33fdb27c78fbfee52e720c0eac690a3bd41d6becf2d5e90bec3f7244fbb3
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --gcc

test_fedora_clang:
  image: greenaddress/fedora_ci@sha256:218c33fdb27c78fbfee52e720c0eac690a3bd41d6becf2d5e90bec3f7244fbb3
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --clang

test_clang:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --clang
    - ./tools/format.sh && git diff --exit-code

test_clang_ndk_armeabi-v7a:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  artifacts:
    expire_in: 1 day
    name: linux_ndk_armeabi-v7a
    when: on_success
    paths:
    - $CI_PROJECT_DIR/$CI_JOB_NAME
  script:
    - cd $CI_PROJECT_DIR
    - mkdir $CI_JOB_NAME
    - ANDROID_NDK=/android-ndk-r17b ./tools/build.sh --install $CI_PROJECT_DIR/$CI_JOB_NAME --ndk armeabi-v7a

test_clang_ndk_arm64-v8a:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  artifacts:
    expire_in: 1 day
    name: linux_ndk_arm64-v8a
    when: on_success
    paths:
    - $CI_PROJECT_DIR/$CI_JOB_NAME
  script:
    - cd $CI_PROJECT_DIR
    - mkdir $CI_JOB_NAME
    - ANDROID_NDK=/android-ndk-r17b ./tools/build.sh --install $CI_PROJECT_DIR/$CI_JOB_NAME --ndk arm64-v8a

test_clang_ndk_x86:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  artifacts:
    expire_in: 1 day
    name: linux_ndk_x86
    when: on_success
    paths:
    - $CI_PROJECT_DIR/$CI_JOB_NAME
  script:
    - cd $CI_PROJECT_DIR
    - mkdir $CI_JOB_NAME
    - ANDROID_NDK=/android-ndk-r17b ./tools/build.sh --install $CI_PROJECT_DIR/$CI_JOB_NAME --ndk x86

test_clang_ndk_x86_64:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  artifacts:
    expire_in: 1 day
    name: linux_ndk_x86_64
    when: on_success
    paths:
    - $CI_PROJECT_DIR/$CI_JOB_NAME
  script:
    - cd $CI_PROJECT_DIR
    - mkdir $CI_JOB_NAME
    - ANDROID_NDK=/android-ndk-r17b ./tools/build.sh --install $CI_PROJECT_DIR/$CI_JOB_NAME --ndk x86_64

test_osx_clang:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --clang

test_osx_ios:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --iphone static

test_osx_clang_ndk_armeabi-v7a:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk armeabi-v7a

test_osx_clang_ndk_arm64-v8a:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk arm64-v8a

test_osx_clang_ndk_x86:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk x86

test_osx_clang_ndk_x86_64:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk x86_64

test_freebsd_gcc:
  tags:
    - freebsd
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --lto=false --gcc

test_freebsd_clang:
  tags:
    - freebsd
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --lto=false --clang

test_windows_mingw_w64_cross:
  image: greenaddress/ci@sha256:5ffe90bec9d392ad07b9ba5cf651663fa3bc3f976f4bbb103cf68ef97ffa17ce
  tags:
    - ga
  artifacts:
    expire_in: 1 hour
    when: on_success
    paths:
    - build-windows-mingw-w64/src/libgreenaddress*
    - build-windows-mingw-w64/src/examples/green-cli*
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --lto=false --mingw-w64

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    expire_in: 14 days
    paths:
    - test_clang_ndk_*/*
    - SHA256SUM.asc
    when: on_success
  script: cd $CI_PROJECT_DIR && /opt/process_release
  dependencies:
  - test_clang_ndk_armeabi-v7a
  - test_clang_ndk_arm64-v8a
  - test_clang_ndk_x86
  - test_clang_ndk_x86_64
