# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Development release"
  lane :dev_release do
  
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "D9W37S9468",
      path: "gaios.xcodeproj",
      code_sign_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)"
    )

    build_ios_app(
      configuration: "Staging",
      scheme: "gaios",
      project: "gaios.xcodeproj",
      clean: true,
      output_directory: "./dev",
      output_name: "Green-dev.ipa",
      disable_package_automatic_updates: true,
      export_method: "ad-hoc",
      export_team_id: "D9W37S9468",
      export_options: {
        provisioningProfiles: {
          "io.blockstream.greendev" => "ed0e54ea-38db-4fe4-ac97-75e3341829d4",
          "io.blockstream.greendev.NotificationService" => "eb72c335-06fe-436d-bfc7-beb27444af39"
        }
      }
    )
    resign(
      ipa: "./dev/Green-dev.ipa",
      signing_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)",
      provisioning_profile: {
        "io.blockstream.green" => "/opt/ios-certs/ed0e54ea-38db-4fe4-ac97-75e3341829d4.mobileprovision",
        "io.blockstream.green.NotificationService" => "/opt/ios-certs/eb72c335-06fe-436d-bfc7-beb27444af39.mobileprovision"
      } 
    )
  end

  desc "Production release"
  lane :prod_release do
  
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "D9W37S9468",
      path: "gaios.xcodeproj",
      code_sign_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)"
    )

    build_ios_app(
      configuration: "Release",
      scheme: "gaios",
      project: "gaios.xcodeproj",
      clean: true,
      output_directory: "./prod",
      output_name: "Green.ipa",
      disable_package_automatic_updates: true,
      export_method: "app-store",
      export_team_id: "D9W37S9468",
      export_options: {
        provisioningProfiles: {
          "io.blockstream.green" => "0006f911-fc84-48d0-a43e-9d84d6475e42",
          "io.blockstream.green.NotificationService" => "f933ea84-de3a-4a58-bb14-bec51ca38592"
        }
      }
    )
    resign(
      ipa: "./prod/Green.ipa",
      signing_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)",
      provisioning_profile: {
        "io.blockstream.green" => "/opt/ios-certs/0006f911-fc84-48d0-a43e-9d84d6475e42.mobileprovision",
        "io.blockstream.green.NotificationService" => "/opt/ios-certs/f933ea84-de3a-4a58-bb14-bec51ca38592.mobileprovision"
      } 
    )
  end

  desc "Build unsigned debug"
  lane :build_unsigned_debug do
  
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "D9W37S9468",
      path: "gaios.xcodeproj",
      code_sign_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)"
    )
    
    build_ios_app(
      configuration: "Debug",
      scheme: "gaios",
      project: "gaios.xcodeproj",
      #silent: true,
      clean: true,
      output_directory: "./debug",
      output_name: "Green-debug.ipa",
      include_symbols: false,
      include_bitcode: false,
      skip_archive: true,
      #skip_package_ipa: true,
      #skip_codesigning: true,
      disable_package_automatic_updates: true,
      sdk: "iphonesimulator",
      destination: "generic/platform=iOS Simulator",
      derived_data_path: "./debug",
      build_path: "./debug",
      xcargs: "ARCHS=arm64",
      export_method: "development",
      export_team_id: "D9W37S9468",
      export_options: {
        provisioningProfiles: {
          "io.blockstream.greendev" => "match Development io.blockstream.greendev",
          "io.blockstream.greendev.NotificationService" => "match Development io.blockstream.greendev.NotificationService"
        }
      }
    )
  end

  desc "Upload apple store"
  lane :upload_apple_store do
    upload_to_testflight(
      apple_id: '1402243590',
      itc_provider: 'D9W37S9468',
      ipa: "prod/Green.ipa",
      username: ENV['FASTLANE_USER'],
      skip_waiting_for_build_processing: true
    )
  end
end
