# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Development release"
  lane :dev_release do
  
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "D9W37S9468",
      path: "gaios.xcodeproj",
      code_sign_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)"
    )

    build_ios_app(
      configuration: "Staging",
      scheme: "gaios",
      project: "gaios.xcodeproj",
      clean: true,
      output_directory: "./dev",
      output_name: "Green-dev.ipa",
      disable_package_automatic_updates: true,
      export_method: "ad-hoc",
      export_team_id: "D9W37S9468",
      export_options: {
        provisioningProfiles: {
          "io.blockstream.greendev" => "match AdHoc io.blockstream.greendev",
          "io.blockstream.greendev.NotificationService" => "match AdHoc io.blockstream.greendev.NotificationService"
        }
      }
    )
    resign(
      ipa: "./dev/Green-dev.ipa",
      signing_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)",
      provisioning_profile: {
        "io.blockstream.greendev" => "/opt/ios-certs/c303d3f8-1d76-4f7d-878a-d59965eef289.mobileprovision",
        "io.blockstream.greendev.NotificationService" => "/opt/ios-certs/81d5e586-e2e0-4d4e-ad5d-efedfad945d9.mobileprovision"
      }
    )
  end

  desc "Production release"
  lane :prod_release do
  
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "D9W37S9468",
      path: "gaios.xcodeproj",
      code_sign_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)"
    )

    build_ios_app(
      configuration: "Release",
      scheme: "gaios",
      project: "gaios.xcodeproj",
      clean: true,
      output_directory: "./prod",
      output_name: "Green.ipa",
      disable_package_automatic_updates: true,
      export_method: "app-store",
      export_team_id: "D9W37S9468",
      export_options: {
        provisioningProfiles: {
          "io.blockstream.green" => "match AppStore io.blockstream.green",
          "io.blockstream.green.NotificationService" => "match AppStore io.blockstream.green.NotificationService"
        }
      }
    )
    resign(
      ipa: "./prod/Green.ipa",
      signing_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)",
      provisioning_profile: {
        "io.blockstream.green" => "/opt/ios-certs/4d77aeda-c66b-4e3b-ae12-a63caf942b94.mobileprovision",
        "io.blockstream.green.NotificationService" => "/opt/ios-certs/660c3b5b-778f-4d53-80ed-a48ca740ed34.mobileprovision"
      }
    )
  end

  desc "Build unsigned debug"
  lane :build_unsigned_debug do
  
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "D9W37S9468",
      path: "gaios.xcodeproj",
      code_sign_identity: "Apple Distribution: Blockstream Corporation (D9W37S9468)"
    )
    
    build_ios_app(
      configuration: "Debug",
      scheme: "gaios",
      project: "gaios.xcodeproj",
      #silent: true,
      clean: true,
      output_directory: "./debug",
      output_name: "Green-debug.ipa",
      include_symbols: false,
      include_bitcode: false,
      skip_archive: true,
      #skip_package_ipa: true,
      #skip_codesigning: true,
      disable_package_automatic_updates: true,
      sdk: "iphonesimulator",
      destination: "generic/platform=iOS Simulator",
      derived_data_path: "./debug",
      build_path: "./debug",
      xcargs: "ARCHS=arm64",
      export_method: "development",
      export_team_id: "D9W37S9468",
      export_options: {
        provisioningProfiles: {
          "io.blockstream.greendev" => "match Development io.blockstream.greendev",
          "io.blockstream.greendev.NotificationService" => "match Development io.blockstream.greendev.NotificationService"
        }
      }
    )
  end

  desc "Upload apple store"
  lane :upload_apple_store do
    upload_to_testflight(
      apple_id: '1402243590',
      itc_provider: 'D9W37S9468',
      ipa: "prod/Green.ipa",
      username: ENV['FASTLANE_USER'],
      skip_waiting_for_build_processing: true
    )
  end
end
