#ifndef GA_SDK_GA_STRINGS_HPP
#define GA_SDK_GA_STRINGS_HPP
#pragma once

#include <string>

namespace ga {
namespace sdk {
    namespace res {

        // FIXME: This file and its source will be autogenerated from transifex sources

        extern const std::string no_outputs;
        extern const std::string send_all_requires_single;
        extern const std::string inconsistent_gauth_data;
        extern const std::string insufficient_funds;
        extern const std::string fee_rate_below_minimum;

    } // namespace res
} // namespace sdk
} // namespace ga

#endif
